###Test get states
GET http://127.0.0.1:8000/api/v1/states?sort_by=created_at&sort_order=desc
Authorization: Bearer 3|XWYbQGgIY3b3FqVJ2MA5VEeATy4hks2UFAOCwoRXbce367b3
Accept: application/json
###Test post states
POST http://127.0.0.1:8000/api/v1/states
Content-Type: application/json
Accept: application/json

{
    "name": "inactive",
    "description": "RegISTratiON is inactive or disabled.",
    "code": "INA",
    "color": "#FF0000",
    "order": 2
}

###Test post states
POST http://127.0.0.1:8000/api/v1/states
Content-Type: application/json
Accept: application/json

{
    "name": "active",
    "description": "RegISTratiON is in use.",
    "code": "ACT",
    "color": "#FF0000",
    "order": 1
}
###Test put states
PUT http://127.0.0.1:8000/api/v1/states/1
Content-Type: application/json
Accept: application/json

{
    "name": "active",
    "description": "RegISTratiON iS iN USE.",
    "code": "ACT",
    "color": "#00FF00",
    "order": 23
}
###Test patch states
PATCH http://127.0.0.1:8000/api/v1/states/1
Content-Type: application/json
Accept: application/json

{
    "order": 1
}
###Test show state
GET http://127.0.0.1:8000/api/v1/states/2
Accept: application/json
###Test get offices
GET http://127.0.0.1:8000/api/v1/offices?page=1&include_hierarchy=1&sort_by=id&sort_order=asc&search=ACTIVO
Accept: application/json
###Test post offices
POST http://127.0.0.1:8000/api/v1/offices
Content-Type: application/json
Accept: application/json

{
    "name" : "SECRETARÍA MUNICIPAL DE ADMINISTRACIÓN Y FINANZAS",
    "initials": "SMAF",
    "level": 1
}
###Test put offices
PUT http://127.0.0.1:8000/api/v1/offices/1
Content-Type: application/json
Accept: application/json

{
    "name" : "SECRETARÍA MUNICIPAL DE ADMINISTRACIÓN Y FINANZAS.",
    "initials": "SMAFI",
    "level": 1
}
###Test patch offices
PATCH http://127.0.0.1:8000/api/v1/offices/41
Content-Type: application/json
Accept: application/json

{
    "state_id": 2
}
###Test show offices
GET http://127.0.0.1:8000/api/v1/offices/41
Accept: application/json
###Test get users
GET http://127.0.0.1:8000/api/v1/users?page=1&sort_by=id&sort_order=desc
Accept: application/json
Authorization: Bearer 4|wMgsWiE1tKJoVh8IoJ3LkD0UXLq2kJ6787CeR1zh0741f0f6

###Test post users
POST http://127.0.0.1:8000/api/v1/users
Content-Type: application/json
Accept: application/json

{
    "first_name": "Alejandro Joel",
    "last_name": "mAGNo LÓpez",
    "phone_number": "61231132",
    "username": "aleLoPez",
    "password": "Danger3@",
    "password_confirmation": "Danger3@",
    "email": "ale@hotmail.com",
    "office_id": 126
}

###Test update users
PUT http://127.0.0.1:8000/api/v1/users/1
Content-Type: application/json
Accept: application/json

{
    "first_name": "Alejandro Joel",
    "last_name": "mAGNo LÓpez",
    "phone_number": "61231132",
    "username": "aleLoPez",
    "password": "Danger33@",
    "password_confirmation": "Danger33@",
    "email": "ale@hotmail.com",
    "office_id": 126
}
###Test patch users
PATCH http://127.0.0.1:8000/api/v1/users/1
Content-Type: application/json
Accept: application/json

{
    "state_id" : 1
}
###Test show users
GET http://127.0.0.1:8000/api/v1/users/1
Accept: application/json
Authorization: Bearer 4|wMgsWiE1tKJoVh8IoJ3LkD0UXLq2kJ6787CeR1zh0741f0f6
###Test login user 
POST http://127.0.0.1:8000/api/v1/login
Content-Type: application/json
Accept: application/json


{
    "username": "GUiLleM.PICharDo",
    "password": "Danger3@"
}

###Test logout user
POST http://127.0.0.1:8000/api/v1/logout
Content-Type: application/json
Authorization: Bearer 3|XWYbQGgIY3b3FqVJ2MA5VEeATy4hks2UFAOCwoRXbce367b3
Accept: application/json