###Test get states
GET http://127.0.0.1:8000/api/v1/states?page=1&sort_by=id
Authorization: Bearer 71|jryYA9HfJRKBB51RfdvXc59U6vW9gZngs59kY9Ksfb85b8d9
Accept: application/json
###Test post states
POST http://127.0.0.1:8000/api/v1/states
Content-Type: application/json
Accept: application/json
Authorization: Bearer 70|93SYTI5K3GIlTokXZsPk9VaCqnbn4G47VtFm53X409144379

{
    "name": "NEW",
    "description": "Item or movement is new.",
    "code": "NEW",
    "color": "#0000FF",
    "order": 0
}

###Test post states
POST http://127.0.0.1:8000/api/v1/states
Content-Type: application/json
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f

{
    "name": "active",
    "description": "RegISTratiON is in use.",
    "code": "ACT",
    "color": "#FF0000",
    "order": 1,
}
###Test put states
PUT http://127.0.0.1:8000/api/v1/states/1
Content-Type: application/json
Accept: application/json

{
    "name": "active",
    "description": "RegISTratiON iS iN USE.",
    "code": "ACT",
    "color": "#00FF00",
    "order": 23
}
###Test patch states
PATCH http://127.0.0.1:8000/api/v1/states/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 21|FioIvl71fOKGcuDSBhmwOnYDbficrKPoQNnTaLVUfd66cf7c

{
    "order": 1
}
###Test show state
GET http://127.0.0.1:8000/api/v1/states/2
Accept: application/json
Authorization: Bearer 21|FioIvl71fOKGcuDSBhmwOnYDbficrKPoQNnTaLVUfd66cf7c
###Test get offices
GET http://127.0.0.1:8000/api/v1/offices?include_hierarchy=1
Accept: application/json
Authorization: Bearer 70|93SYTI5K3GIlTokXZsPk9VaCqnbn4G47VtFm53X409144379

###Test post offices
POST http://127.0.0.1:8000/api/v1/offices
Content-Type: application/json
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f

{
    "name" : "SECRETARÍA MUNICIPAL DE ADMINISTRACIÓN Y FINANZAS",
    "initials": "SMAF",
    "level": 1,
}
###Test put offices
PUT http://127.0.0.1:8000/api/v1/offices/1
Content-Type: application/json
Accept: application/json

{
    "name" : "SECRETARÍA MUNICIPAL DE ADMINISTRACIÓN Y FINANZAS.",
    "initials": "SMAFI",
    "level": 1
}
###Test patch offices
PATCH http://127.0.0.1:8000/api/v1/offices/41
Content-Type: application/json
Accept: application/json

{
    "state_id": 2
}
###Test show offices
GET http://127.0.0.1:8000/api/v1/offices/41
Authorization: Bearer 15|KLgOgvpBWJqdXkYrJk1Gen3t8gVu0yAHNV8NShoNc19b0661
Accept: application/json
###Test get users &sort_by=office_name&sort_order=desc
GET http://127.0.0.1:8000/api/v1/users?page=1&sort_by=id
Accept: application/json
Authorization: Bearer 57|1NevDakbQtrZH1FpBmn4CsA68f3VcZdKwmCaPETo5615b660
###Test post users
POST http://127.0.0.1:8000/api/v1/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer 66|gsmhoOu5weAAbmsbBDmGXGEb6WuX2ydk9W2LDXQwd3b68a51

{
    "first_name": " Jose Pato",
    "last_name": "mAGNo LÓpez",
    "phone_number": "61231132",
    "username": "aleLoPez",
    "password": "Danger3@",
    "password_confirmation": "Danger3@",
    "email": "JosePato@hotmail.com",
    "office_id": 126
}

###Test update users
PUT http://127.0.0.1:8000/api/v1/users/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer 18|xdEnNKoqit57NuIF6HygfR8JqUbQ8TzPHwifpuK8991350da

{
    "first_name": "Alejandro Joel",
    "last_name": "mAGNo LÓpez",
    "phone_number": "61231132",
    "username": "aleLoPez",
    "password": "Danger33@",
    "password_confirmation": "Danger33@",
    "email": "aleA@hotmail.com",
    "office_id": 126
}
###Test patch users
PATCH http://127.0.0.1:8000/api/v1/users/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer 21|FioIvl71fOKGcuDSBhmwOnYDbficrKPoQNnTaLVUfd66cf7c

{
    "first_name" : "MATEO"
   
}
###Test show users
GET http://127.0.0.1:8000/api/v1/users/1
Accept: application/json
Authorization: Bearer 65|Lx94gefB2d15aqctlLLnnDEoD8LFqaUWjkO49s88cc90f1b5

# Authorization: Bearer 4|wMgsWiE1tKJoVh8IoJ3LkD0UXLq2kJ6787CeR1zh0741f0f6
###Test login user 
###TOKEN USER: 16|KNiYrLygWGeiYEzZnYQMUNLaPqQCHeYaL4deiu8wab9e3620
POST http://127.0.0.1:8000/api/v1/login
Content-Type: application/json
Accept: application/json

{
    "username": "ZRIVAS",
    "password": "Danger3@"
}

###Test logout user
POST http://127.0.0.1:8000/api/v1/logout
Content-Type: application/json
Authorization: Bearer 38|GIJxiWJE1NbDz625dZ7LubUAsgTJv0BTj5G558s489eda5ec
# Authorization: Bearer 28|re2vU9qxuCEdSKHrbpmpTT41Yl2kXwzscKQVG2iW27938767
Accept: application/json

###Test get permission
GET http://127.0.0.1:8000/api/v1/permissions?page=3&sort_by=id
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f

###Test post permission
POST http://127.0.0.1:8000/api/v1/permissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer 74|3q1LebInDCDA0yUpKg0gj88sJAA79A1OfpmsUqAa87077f1d

{
    "name": "delete increase_types"
}
###Test show permission
GET http://127.0.0.1:8000/api/v1/permissions/1
Accept: application/json
Authorization: Bearer 20|HZ0mam02j1nZ3nDWbgqAlrxG2mymkEU11mlrU0T06d3f1c40
###Test update permission
PUT http://127.0.0.1:8000/api/v1/permissions/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f

{
    "name": "REGister STAtes",
}
###Test patch permission
PATCH http://127.0.0.1:8000/api/v1/permissions/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f

{
    "name": "RegisTer states",
}
###Test get roles
GET http://127.0.0.1:8000/api/v1/roles?page=1&sort_by=id&sort_order=asc
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f
###Test post roles
POST http://127.0.0.1:8000/api/v1/roles
Content-Type: application/json
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f

{
    "name": "test",
}
###Test put roles
PUT http://127.0.0.1:8000/api/v1/roles/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 7|ORfkdK9zgDkoCHB7Zim7HqPGq5wA4PXrW6MC2Vx3c13a89ee

{
}
###Test patch roles
PATCH http://127.0.0.1:8000/api/v1/roles/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 74|3q1LebInDCDA0yUpKg0gj88sJAA79A1OfpmsUqAa87077f1d
# {
#     "menus" : [1, 2]
# }

{
    "permissions": [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30 ,31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]
}
###Test show roles
GET http://127.0.0.1:8000/api/v1/roles/1
Accept: application/json
Authorization: Bearer 63|pvuFWxcfxwq7PjQ9R7Q0djaK57ThYzquKISmmp5I07038285

###Test get employees
GET http://127.0.0.1:8000/api/v1/employees
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f

###Test post employees
POST http://127.0.0.1:8000/api/v1/employees
Content-Type: application/json
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f


{
    "first_name": "GErardo Arturo",
    "last_name" :"vargas",
    "phone_number": "72372820",
    "position": "ar",
    "office_id": 1,

}
###Test update employees
PUT http://127.0.0.1:8000/api/v1/employees/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f

{
"first_name": "GErardo Arturo",
}
###Test patch employees
PATCH http://127.0.0.1:8000/api/v1/employees/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f

{
"first_name": "<>/",
}
###Test show employees
GET http://127.0.0.1:8000/api/v1/employees/1
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f
####Test get menus
GET http://127.0.0.1:8000/api/v1/menus?include_hierarchy=0
Authorization: Bearer 70|93SYTI5K3GIlTokXZsPk9VaCqnbn4G47VtFm53X409144379
####Test post menus
POST http://127.0.0.1:8000/api/v1/menus
Content-Type: application/json
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f

{
    "label": "register_users",
    "route": "/users/register",
    "icon": "pi-plus-circle",
    "level": 2,
    "parent": 2
}

####Test put menus
PUT http://127.0.0.1:8000/api/v1/menus/1
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f
Content-Type: application/json

{
    "": ""
}
####Test patch menus
PATCH http://127.0.0.1:8000/api/v1/menus/6
Accept: application/json
Authorization: Bearer 56|D3qWCjgybYJ9oLmLfbkeXsj7BrkFhTOtpxZPy8Gqffca252f
Content-Type: application/json

{
    "order": 0,
    "parent": 5,
    "level": 3
}
####Test show menus
GET http://127.0.0.1:8000/api/v1/menus/1
Accept: application/json
Authorization: Bearer 72|5N5QLBZP5R29exZkssB6GBjnLwidjx4nh0Xh59BS5c05d562
###GET motives
GET http://127.0.0.1:8000/api/v1/motives
Accept: application/json
Authorization: Bearer 72|5N5QLBZP5R29exZkssB6GBjnLwidjx4nh0Xh59BS5c05d562
###POST motives
POST http://127.0.0.1:8000/api/v1/motives
Accept: application/json
Authorization: Bearer 72|5N5QLBZP5R29exZkssB6GBjnLwidjx4nh0Xh59BS5c05d562
Content-Type: application/json

{
    "name": "DECOMMISSIONING",
    "description": "Official removal of an item from active use due to obsolescence or poor condition."
}
###PUT motives
PUT http://127.0.0.1:8000/api/v1/motives/1
Accept: application/json
Authorization: Bearer 72|5N5QLBZP5R29exZkssB6GBjnLwidjx4nh0Xh59BS5c05d562
Content-Type: application/json

{
    "name": "DECOMMISSIONING",
    "description": "Official removal of an item from active use due to obsolescence or poor condition."
}
###PATCH motives
PATCH http://127.0.0.1:8000/api/v1/motives/1
Accept: application/json
Authorization: Bearer 72|5N5QLBZP5R29exZkssB6GBjnLwidjx4nh0Xh59BS5c05d562
Content-Type: application/json

{
    "state_id": 1
}
###SHOW motives
GET http://127.0.0.1:8000/api/v1/motives/3
Accept: application/json
Authorization: Bearer 72|5N5QLBZP5R29exZkssB6GBjnLwidjx4nh0Xh59BS5c05d562
###GET note types
GET http://127.0.0.1:8000/api/v1/note_types
Accept: application/json
Authorization: Bearer 73|ICyad6zRZdYLN9RFVoxVn9XHqsauAYR1KDGY04U8548cf0ca
###POST note types
POST http://127.0.0.1:8000/api/v1/note_types
Accept: application/json
Authorization: Bearer 73|ICyad6zRZdYLN9RFVoxVn9XHqsauAYR1KDGY04U8548cf0ca
Content-Type: application/json

{
    "name": "BUILDING AND LAND RECORD",
    "description": "Document related to the inspection or evaluation of buildings and land."
}
###PUT note types
PUT http://127.0.0.1:8000/api/v1/note_types/1
Accept: application/json
Authorization: Bearer 72|5N5QLBZP5R29exZkssB6GBjnLwidjx4nh0Xh59BS5c05d562
Content-Type: application/json

{
    "name": "DECOMMISSIONING",
}
###PATCH note types
PATCH http://127.0.0.1:8000/api/v1/note_types/1
Accept: application/json
Authorization: Bearer 73|ICyad6zRZdYLN9RFVoxVn9XHqsauAYR1KDGY04U8548cf0ca
Content-Type: application/json

{
    "state_id": 1
}
###SHOW note types
GET http://127.0.0.1:8000/api/v1/note_types/2
Accept: application/json
Authorization: Bearer 73|ICyad6zRZdYLN9RFVoxVn9XHqsauAYR1KDGY04U8548cf0ca
###GET increase types
GET http://127.0.0.1:8000/api/v1/increase_types
Accept: application/json
Authorization: Bearer 74|3q1LebInDCDA0yUpKg0gj88sJAA79A1OfpmsUqAa87077f1d
###POST increase types
POST http://127.0.0.1:8000/api/v1/increase_types
Accept: application/json
Authorization: Bearer 74|3q1LebInDCDA0yUpKg0gj88sJAA79A1OfpmsUqAa87077f1d
Content-Type: application/json

{
    "name": "CONSTRUCTION",
    "description": "Process or result of building infrastructure or structures."
}
###PUT increase types
PUT http://127.0.0.1:8000/api/v1/increase_types/1
Accept: application/json
Authorization: Bearer 72|5N5QLBZP5R29exZkssB6GBjnLwidjx4nh0Xh59BS5c05d562
Content-Type: application/json

{
    "name": "DECOMMISSIONING",
}
###PATCH increase types
PATCH http://127.0.0.1:8000/api/v1/increase_types/1
Accept: application/json
Authorization: Bearer 74|3q1LebInDCDA0yUpKg0gj88sJAA79A1OfpmsUqAa87077f1d
Content-Type: application/json

{
    "state_id":1
}
###SHOW increase types
GET http://127.0.0.1:8000/api/v1/increase_types/2
Accept: application/json
Authorization: Bearer 74|3q1LebInDCDA0yUpKg0gj88sJAA79A1OfpmsUqAa87077f1d
